### ISSUE TITLE
This doesnt work

### ISSUE THREAD

**Issue by pYbiz** [Mar-tin-G/ExternalLinkInNewWindow#5]
Doesnt open in a new window

**Comment by Mar-tin-G** [comment]
Did you configure the extension properly after installing it? Please check in your ACP → Extensions → External Link In New Window → Settings:

The options labeled with `Open external links in new window for …` must be enabled for your use case.

**Comment by Mar-tin-G** [comment]
@pYbiz please re-open with more information if the problem still exists.
