### ISSUE TITLE
v1.1.0 doesn't work in phpBB v3.2.7 (current)

### ISSUE THREAD

**Issue by luuvasara** [Mar-tin-G/ExternalLinkInNewWindow#6]
Unknown reason. Was working with v1.0.1 in phpBB v3.2.5.
Same concluded in https://www.phpbb.com/customise/db/extension/external_link_in_new_window/support/topic/203926

**Comment by Galixte** [comment]
Hi,

on the subject that you indicated it asked to list the extensions activated on your board, so you know what to do in awaiting the author extension answer.

@Mar-tin-G, could you take a look, please?

Regards.

**Comment by luuvasara** [comment]
Indeed, I disabled all extensions and tried to enable them one by one to find out but the issue doesn't reoccur. Would appear to focus on "working on fresh install".

Clean Name:
    david63/activesessions
Description:
    Adds an Admin option to display the current active user sessions.
Version:
    2.1.0

Clean Name:
    phpbb/boardrules
Description:
    An extension which allows you to create a set of rules for your phpBB forum
Version:
    2.1.1

Clean Name:
    phpbb/googleanalytics
Description:
    An extension that allows administrators to easily add their Google Analytics tracking code to their phpBB forum.
Version:
    1.0.4

Clean Name:
    david63/logsearches
Description:
    Creates a log of searched enquiries.
Version:
    2.1.0-rc1

Clean Name:
    david63/logconnections
Description:
    This extension will log user connections, failed logins and new users.
Version:
    2.1.0-rc2

Clean Name:
    dmzx/notifyadmin
Description:
    When a new user registers on your board, a short e-mail with basic user info will be sent to all administrators of the board.
Version:
    1.0.1

Clean Name:
    phpbb/pages
Description:
    An extension which allows you to add static pages to your phpBB forum
Version:
    2.0.3

Clean Name:
    vse/passwordstrength
Description:
    An extension for phpBB that will show users how strong (or weak) their password is as they type it into the password field when creating or updating their account.
Version:
    1.2.2

Clean Name:
    dmzx/pmregbar
Description:
    This extension will add PM Notify & Guest Register bar.
Version:
    1.0.5

Clean Name:
    stevotvr/flair
Description:
    An extension to add flair to user profiles
Version:
    1.2.1

Clean Name:
    david63/topicagewarning
Description:
    This extension displays a warning to users when they attempt to reply to a topic that has had no replies for a specified amount of time.
Version:
    2.1.0-rc2

**Comment by Mar-tin-G** [comment]
@qriff so I understand that after re-enabling the extension it now works. Thanks for reporting back, please re-open the issue if the problem shows again.
