### ISSUE TITLE
security issue with target="_blank"

### ISSUE THREAD

**Issue by thib3113** [Mar-tin-G/ExternalLinkInNewWindow#8]
Hello, opening a link with target="_blank" can lead to a security issue . 
Read this : https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

The solution is to add `rel=”noopener noreferrer”` in you'r links with "_blank" ( what I didn't see on your repo )

**Comment by Mar-tin-G** [comment]
Thanks for the issue @thib3113, will be fixed in the next release!
